version: '3.3'
services:
  postgres:
    container_name: postgres_dr_consulta
    image: postgres:15
    restart: unless-stopped
    ports:
      - '5432:${DB_PORT}'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - PGTZ=America/Sao_Paulo
